# Generated by Django 5.0.6 on 2024-07-03 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('bmi', models.FloatField(editable=False)),
                ('membership_type', models.CharField(choices=[('WT', 'Weight Training'), ('C', 'Cardio'), ('B', 'Both')], max_length=2)),
                ('admission_number', models.PositiveIntegerField()),
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
