# Generated by Django 5.0.6 on 2024-07-03 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='admission_number',
            field=models.PositiveIntegerField(default=0, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='FeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_payment', models.DateField(default=django.utils.timezone.now)),
                ('duration_in_months', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.customer')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.PositiveIntegerField(help_text='Month number (1 for January, 2 for February, etc.)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.customer')),
            ],
        ),
    ]
