# Generated by Django 5.0.6 on 2024-07-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_remove_customer_membership_type_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bmi',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in centimeters', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
