# Generated by Django 5.0.6 on 2024-08-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_customer_date_of_birth_alter_feedetail_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'phone_no')},
        ),
    ]
