# Generated by Django 5.0.7 on 2024-09-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytable',
            name='name',
            field=models.CharField(choices=[('F', 'Fees'), ('A', 'Admission'), ('O', 'Other')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='category',
            field=models.CharField(choices=[('F', 'Fees'), ('A', 'Admission'), ('O', 'Other')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=9),
        ),
    ]
