# Generated by Django 5.0.6 on 2024-10-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_categorytable_name_alter_feedetail_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetail',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=10),
        ),
        migrations.AlterUniqueTogether(
            name='feedetail',
            unique_together={('month', 'year', 'category', 'customer')},
        ),
    ]
