# Generated by Django 5.0.6 on 2024-10-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_feedetail_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytable',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.categorytable'),
        ),
    ]
