# Generated by Django 5.0.6 on 2024-10-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_alter_categorytable_name_alter_feedetail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytable',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
