# Generated by Django 5.0.6 on 2024-12-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_alter_categorytable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedetail',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=12),
        ),
    ]
