# Generated by Django 5.0.6 on 2024-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_alter_feedetail_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='health',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
