# Generated by Django 5.0.6 on 2024-12-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_alter_customer_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytable',
            name='is_fees',
            field=models.BooleanField(default=False),
        ),
    ]
