# Generated by Django 5.0.6 on 2024-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_categorytable_is_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytable',
            name='no_of_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
